---
- name: copie fichier webapp
  hosts: all
  become: true
  tasks:
    - name: copy file
      copy:
        src: /var/lib/jenkins/workspace/JENKINES/webapp/target/webapp.war
        dest: /opt/tomcat/latest/webapps


