---
- name: copie fichier webapp
  hosts: all
  become: true


  tasks:

    - name: copy file
      template:
        copy:
        src: /home/centos/JENKINES/webapp/target/webapp.war
        dest: /opt/tomcat/latest/webapps

